[package]
name = "url2big"
version = "0.1.0"
authors = ["Jov4n <jo.van.bundalo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0-alpha.1"
actix-web = "2"
actix-rt = "1"
